/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiler;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miguel.villalobos
 */
public class Tablas extends javax.swing.JFrame {
    private final String[] headerSimbolos = {"Simbolos", "Tipo", "Descripción"};
    private final String[] headerReservadas = {"Palabra reservada", "Tipo", "Descripcion"};
    private DefaultTableModel tableSimbolos = new DefaultTableModel(null, headerSimbolos);
    private DefaultTableModel tableReservadas = new DefaultTableModel(null, headerReservadas);
    /**
     * Creates new form Tablas
     */
    public Tablas() {
        Database dbtable = new Database();
        ArrayList<ArrayList> simbolos = dbtable.getSimbolos();
        for(ArrayList row : simbolos){
            tableSimbolos.addRow(row.toArray());
        }
        
        ArrayList<ArrayList> palabras = dbtable.getReservadas();
        for(ArrayList row : palabras){
            tableReservadas.addRow(row.toArray());
        }
        initComponents();
        setTitle("Tablas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrarTablas = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelSimbolos = new javax.swing.JPanel();
        scrollPanelSimbolos = new javax.swing.JScrollPane();
        jTableSimbolos = new javax.swing.JTable();
        panelReservadas = new javax.swing.JPanel();
        scrollPanelReservadas = new javax.swing.JScrollPane();
        jTableReservadas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cerrarTablas.setText("Cerrar");
        cerrarTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarTablasActionPerformed(evt);
            }
        });

        jTableSimbolos.setModel(tableSimbolos);
        scrollPanelSimbolos.setViewportView(jTableSimbolos);

        javax.swing.GroupLayout panelSimbolosLayout = new javax.swing.GroupLayout(panelSimbolos);
        panelSimbolos.setLayout(panelSimbolosLayout);
        panelSimbolosLayout.setHorizontalGroup(
            panelSimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimbolosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelSimbolos, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSimbolosLayout.setVerticalGroup(
            panelSimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSimbolosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelSimbolos)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Simbolos", panelSimbolos);

        jTableReservadas.setModel(tableReservadas);
        scrollPanelReservadas.setViewportView(jTableReservadas);

        javax.swing.GroupLayout panelReservadasLayout = new javax.swing.GroupLayout(panelReservadas);
        panelReservadas.setLayout(panelReservadasLayout);
        panelReservadasLayout.setHorizontalGroup(
            panelReservadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelReservadas, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelReservadasLayout.setVerticalGroup(
            panelReservadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelReservadas)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Palabras Reservadas", panelReservadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cerrarTablas))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrarTablas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarTablasActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cerrarTablasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarTablas;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableReservadas;
    private javax.swing.JTable jTableSimbolos;
    private javax.swing.JPanel panelReservadas;
    private javax.swing.JPanel panelSimbolos;
    private javax.swing.JScrollPane scrollPanelReservadas;
    private javax.swing.JScrollPane scrollPanelSimbolos;
    // End of variables declaration//GEN-END:variables
}
